homeassistant:
  # Name of the location where Home Assistant is running
  name: The Castle
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 480
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
    themes: !include_dir_merge_named themes/

lovelace:
 mode: yaml

# Enables configuration UI
config:

# system health enable
system_health:

hacs:
  token: !secret  hacs_token
  sidepanel_title: Community

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
#  api_password: !secret http_password
#  base_url: !secret http_url
#  ssl_certificate: !secret cert_path
#  ssl_key: !secret cert_key_path

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
mobile_app:

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

rest_command:
  google_backup:
    url: !secret google_backup_url
    timeout: '300'


recorder:
  purge_interval: 1
  purge_keep_days: 14
  exclude:
     domains:
      - automation
      - media_player


influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

panel_iframe:
  router:
    title: 'Router'
    url: !secret weblink1
    icon: mdi:router-wireless
  portainer:
    title: 'Portainer'
    url: !secret portainer
    icon: mdi:docker
  urbackup:
    title: 'UrBackup'    
    url: !secret urbackup
    icon: mdi:backup-restore


# Cloud
cloud:   
  alexa:                                                                      
    filter:                                                                   
      include_entities:                                                       
        - switch.wall_monitor                                                 
        - switch.sonoff_1_relay                                               
        - switch.living_room_ceiling_fan_relay
        - switch.cat_light


hassio:




ecobee:
  api_key: !secret ecobee_key

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
    radius: 150
    minimum_magnitude: 0.0
    latitude: !secret home_lat
    longitude: !secret home_lon

hue:
  bridges:
    - host: !secret hue_ip


ifttt:
  key: !secret ifttt_key


simplisafe:
  accounts:
    - username: !secret alarm_username
      password: !secret alarm_password
      
spotify:
  client_id:  !secret spotify_clicnet_id2
  client_secret: !secret spotify_clicnet_secret2


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'en-uk'

wemo:
  static:
    - !secret wemo1_ip
    - !secret wemo2_ip
    - !secret wemo3_ip
    - !secret wemo4_ip
    - !secret wemo5_ip
    - !secret wemo6_ip

#wink:

###############################################################
######  Include Files
###############################################################

#automation: !include includes/automations.yaml
camera: !include includes/cameras.yaml
#device_tracker: !include includes/trackers.yaml
input_boolean: !include includes/input_boolean.yaml
input_select:  !include includes/input_selects.yaml
input_number: !include includes/input_numbers.yaml
light: !include includes/lights.yaml
notify: !include includes/notifiers.yaml
remote: !include includes/remote.yaml
script: !include includes/scripts.yaml
weather: !include includes/weather.yaml
#weblink: !include includes/weblinks.yaml
#wink: !include includes/wink.yaml

###############################################################
######  Merge Include Files
###############################################################
automation: !include_dir_merge_list includes/automations
media_player:  !include_dir_merge_list  includes/media_players
scene: !include_dir_merge_list includes/scenes
sensor: !include_dir_merge_list includes/sensors
zone: !include_dir_list includes/zones

